### ISSUE TITLE
Error while loading spigotboard

### ISSUE THREAD

**Issue by jediultras** [yPedx/SpigotBoard#17]
idk why, but my console always give me an error of failed spigotboard loading...

this is the error conole code:

[19:47:09] [Server thread/ERROR]: Error occurred while enabling SpigotBoard vv2.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at me.developer.ypedx.SpigotBoard.onEnable(SpigotBoard.java:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:128) ~[craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[craftbukkit-1.12.2.jar:git-Bukkit-9060bfa]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 12 more
[19:47:09] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.15.0.1

**Comment by yPedx** [comment]
You need to use Spigot, not CraftBukkit.

**Comment by jediultras** [comment]
ok thanks, solved

**Comment by jediultras** [comment]
this is the only error:

[12:56:23] [Server thread/INFO]: [SpigotBoard] Enabling SpigotBoard vv2.2.1
[12:56:24] [Server thread/ERROR]: [SpigotBoard] PlaceholderAPI not found, disabling support for PlaceholderAPI.

**Comment by yPedx** [comment]
That's normal. See if it helps installing PlaceholderAPI.

**Comment by jediultras** [comment]
installed, no error, but no scoreboard... idk...

**Comment by jediultras** [comment]
i resetted the spigotboard files and now works, thanks for the helps and the fast responses!!!

**Comment by yPedx** [comment]
All good!
