### ISSUE TITLE
Plugin Error PaperSpigot 1.12.2

### ISSUE THREAD

**Issue by artemati1** [yPedx/SpigotBoard#35]
Error:
[14:53:21 ERROR]: Could not pass event PlayerJoinEvent to SpigotBoard vv2.2.4
java.lang.NoSuchMethodError: org.bukkit.scoreboard.Scoreboard.registerNewObjective(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/bukkit/scoreboard/Objective;
        at me.ypedx.spigotboard.scoreboard.Handler.createScoreboard(Handler.java:36) ~[?:?]
        at me.ypedx.spigotboard.scoreboard.Handler.setScoreboard(Handler.java:59) ~[?:?]
        at me.ypedx.spigotboard.events.Join.onJoin(Join.java:24) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor67.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by artemati1** [comment]
And Warning:
[14:53:32 WARN]: [SpigotBoard] Task #14 for SpigotBoard vv2.2.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.scoreboard.Scoreboard.registerNewObjective(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/bukkit/scoreboard/Objective;
        at me.ypedx.spigotboard.scoreboard.Handler.createScoreboard(Handler.java:36) ~[?:?]
        at me.ypedx.spigotboard.scoreboard.Handler.updateScoreboard(Handler.java:75) ~[?:?]
        at me.ypedx.spigotboard.utils.Timer.run(Timer.java:12) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by yPedx** [comment]
This should be fixed in the newest version of SpigotBoard (v2.2.5) Thank you for reporting it!
