### ISSUE TITLE
Plugin Error PaperSpigot 1.12.2

### ISSUE THREAD

**Issue by artemati1** [yPedx/SpigotBoard#36]
Error: 
[09:21:14] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to SpigotBoard vv2.2.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Paper.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at me.ypedx.spigotboard.scoreboard.Handler.replaceValues(Handler.java:104) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.fixString(Handler.java:88) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.setScores(Handler.java:52) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.setScoreboard(Handler.java:59) ~[?:?]
	at me.ypedx.spigotboard.events.Join.onJoin(Join.java:24) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor67.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper.jar:git-Paper-1618]
	... 14 more

**Comment by artemati1** [comment]
Warning:
[09:21:18] [Server thread/WARN]: [SpigotBoard] Task #14 for SpigotBoard vv2.2.5 generated an exception
java.lang.NullPointerException: null
	at me.ypedx.spigotboard.scoreboard.Handler.replaceValues(Handler.java:104) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.fixString(Handler.java:88) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.setScores(Handler.java:52) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.Handler.updateScoreboard(Handler.java:77) ~[?:?]
	at me.ypedx.spigotboard.utils.Timer.run(Timer.java:12) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by yPedx** [comment]
If you're sure you have both Vault & Essentials installed, I think there's something weird about Paperspigot. I've tested SpigotBoard on 1.12 and there doesn't seem to be any issues for me whether I have Vault & Essentials or not.

**Comment by artemati1** [comment]
Version 2.2.2 works fine, unlike the last version.

**Comment by yPedx** [comment]
This should be fixed in the latest version (2.2.7)
