### ISSUE TITLE
Couldn't load plugin\SpigotBoard 3.0.0-BETA.jar

### ISSUE THREAD

**Issue by MrMatttw** [yPedx/SpigotBoard#44]
Hi, this maybe a awesome plugin, but my server(Spigot 1.14.4) could NOT load the plugin version 3.0.0-BETA. Here are the logs:
Could not load 'plugins\SpigotBoard 3.0.0-BETA.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:261) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by yPedx** [comment]
Found the issue. I'll remove the api-version property in the plugin.yml and push an update in a few hours.

**Comment by MrMatttw** [comment]
Thanks! Excited!

**Comment by yPedx** [comment]
This issue has been resolved in the newest version (3.0.1-BETA)
