### ISSUE TITLE
Askyblock placeholder error

### ISSUE THREAD

**Issue by Jonspeeth** [yPedx/SpigotBoard#47]
When I install the askyblock placeholder and have it on spigotboard I get spammed in the console with this, and I can no longer see the spigotboard

[23:10:03] [Server thread/WARN]: [SpigotBoard] Task #36 for SpigotBoard v3.0.3 generated an exception
java.lang.NullPointerException
	at com.extendedclip.papi.expansion.askyblock.ASkyBlockExpansion.onPlaceholderRequest(ASkyBlockExpansion.java:148) ~[?:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.replaceAndColor(ScoreboardHandler.java:167) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.setLines(ScoreboardHandler.java:135) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.updateScoreboard(ScoreboardHandler.java:78) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardTask.run(ScoreboardTask.java:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by yPedx** [comment]
I apologize for the late reply! It seems that this error is coming from ASkyblock, and not SpigotBoard. Have you checked with the developers of ASkyblock if there's something wrong there?
