### ISSUE TITLE
SpigotBoard Not Working

### ISSUE THREAD

**Issue by Nameless12127** [yPedx/SpigotBoard#55]
https://mclo.gs/BxCPbOg

**Comment by Petmic1337** [comment]
Same here (Spigot Version 1.21 - Java 21 LTS):

`[Server thread/WARN]: [SpigotBoard] Task #50 for SpigotBoard v3.0.4 generated an exception
java.lang.NumberFormatException: For input string: "121-R0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at me.ypedx.spigotboard.util.VersionHandler.colorsWillDisappear(VersionHandler.java:29) ~[?:?]
	at me.ypedx.spigotboard.util.VersionHandler.getMaxTitleLength(VersionHandler.java:24) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.setTitle(ScoreboardHandler.java:109) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.getNewScoreboard(ScoreboardHandler.java:92) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.addBoardToPlayer(ScoreboardHandler.java:32) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.updateScoreboard(ScoreboardHandler.java:70) ~[?:?]
	at me.ypedx.spigotboard.scoreboard.ScoreboardTask.run(ScoreboardTask.java:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1425) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by Petmic1337** [comment]
> Same here (Spigot Version 1.21 - Java 21 LTS):
> 
> `[Server thread/WARN]: [SpigotBoard] Task #50 for SpigotBoard v3.0.4 generated an exception java.lang.NumberFormatException: For input string: "121-R0" at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?] at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?] at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?] at me.ypedx.spigotboard.util.VersionHandler.colorsWillDisappear(VersionHandler.java:29) ~[?:?] at me.ypedx.spigotboard.util.VersionHandler.getMaxTitleLength(VersionHandler.java:24) ~[?:?] at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.setTitle(ScoreboardHandler.java:109) ~[?:?] at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.getNewScoreboard(ScoreboardHandler.java:92) ~[?:?] at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.addBoardToPlayer(ScoreboardHandler.java:32) ~[?:?] at me.ypedx.spigotboard.scoreboard.ScoreboardHandler.updateScoreboard(ScoreboardHandler.java:70) ~[?:?] at me.ypedx.spigotboard.scoreboard.ScoreboardTask.run(ScoreboardTask.java:16) ~[?:?] at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1425) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4288-Spigot-fb8fb72-8f26c30] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**WICHTIGER HINWEIS**
SERVERUPDATE 1.21.1 BEHEBT DEN FEHLER. PLUGIN FUNKTIONIERT.

**IMPORTANT NOTE**
SERVERUPDATE 1.21.1 FIXES THE ERROR. PLUGIN WORKS.
